# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.tests.csproj'
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
  displayName: 'Run Tests'

- task: NodeTool@0
  inputs:
    versionSpec: "14.x"
  displayName: "Install Node.js"

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Sonar'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'DevOps-frontend'
    cliProjectName: 'DevOps-frontend'
    cliSources: './client'

- script: |
    cd ./client
    npm install
    npm run build
  displayName: "npm install and build"

- task: SonarQubeAnalyze@5

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'