# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: Install .net 6
  inputs:
    packageType: sdk
    version: 6.0.x

- task: UseNode@1
  displayName: Install Node
  inputs:
   version: 14.x    
  
- task: DotNetCoreCLI@2
  displayName: Build .Net
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    
- task: DotNetCoreCLI@2
  displayName: Test .Net
  inputs:
    command: 'test'
    projects: '**/*.tests.csproj'
    arguments: "/p:CollectCoverage=true /p:CoverletOutputFormat=opencover"

- task: Npm@1
  displayName: Install node modules
  inputs:
    command: 'install'
    workingDir: 'client'
    
- task: Npm@1
  displayName: Build UI
  inputs:
    customCommand: 'build'
    workingDir: 'client'